# import required libray

In [33]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score

In [34]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline

In [35]:
import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='XeaAWDu0NTFq6Wd1KkU_9kiMsC5f8bAki0X4MI77fHRP',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'ibmdepolyment-donotdelete-pr-mut3vz0xh6wsjn'
object_key = 'PM_train.xlsx'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']

dataset_train = pd.read_excel(body.read())
dataset_train
import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='XeaAWDu0NTFq6Wd1KkU_9kiMsC5f8bAki0X4MI77fHRP',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'ibmdepolyment-donotdelete-pr-mut3vz0xh6wsjn'
object_key = 'PM_train.xlsx'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']

dataset_train = pd.read_excel(body.read())
dataset_train.head()


id  cycle  setting1  setting2  setting3      s1      s2       s3       s4  \
0   1      1   -0.0007   -0.0004       100  518.67  641.82  1589.70  1400.60   
1   1      2    0.0019   -0.0003       100  518.67  642.15  1591.82  1403.14   
2   1      3   -0.0043    0.0003       100  518.67  642.35  1587.99  1404.20   
3   1      4    0.0007    0.0000       100  518.67  642.35  1582.79  1401.87   
4   1      5   -0.0019   -0.0002       100  518.67  642.37  1582.85  1406.22   

      s5  ...     s12      s13      s14     s15   s16  s17   s18  s19    s20  \
0  14.62  ...  521.66  2388.02  8138.62  8.4195  0.03  392  2388  100  39.06   
1  14.62  ...  522.28  2388.07  8131.49  8.4318  0.03  392  2388  100  39.00   
2  14.62  ...  522.42  2388.03  8133.23  8.4178  0.03  390  2388  100  38.95   
3  14.62  ...  522.86  2388.08  8133.83  8.3682  0.03  392  2388  100  38.88   
4  14.62  ...  522.19  2388.04  8133.80  8.4294  0.03  393  2388  100  38.90   

       s21  
0  23.4190  
1  23.4236  
2  23.3442  
3  23.3739  
4  23.4044  

[5 rows x 26 columns]

In [36]:
import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='XeaAWDu0NTFq6Wd1KkU_9kiMsC5f8bAki0X4MI77fHRP',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'ibmdepolyment-donotdelete-pr-mut3vz0xh6wsjn'
object_key = 'PM_test.xlsx'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']

dataset_test = pd.read_excel(body.read())
dataset_test.head()


id  cycle  setting1  setting2  setting3      s1      s2       s3       s4  \
0   1      1    0.0023    0.0003       100  518.67  643.02  1585.29  1398.21   
1   1      2   -0.0027   -0.0003       100  518.67  641.71  1588.45  1395.42   
2   1      3    0.0003    0.0001       100  518.67  642.46  1586.94  1401.34   
3   1      4    0.0042    0.0000       100  518.67  642.44  1584.12  1406.42   
4   1      5    0.0014    0.0000       100  518.67  642.51  1587.19  1401.92   

      s5  ...     s12      s13      s14     s15   s16    s17     s18    s19  \
0  14.62  ...  521.72  2388.03  8125.55  8.4052  0.03  392.0  2388.0  100.0   
1  14.62  ...  522.16  2388.06  8139.62  8.3803  0.03  393.0  2388.0  100.0   
2  14.62  ...  521.97  2388.03  8130.10  8.4441  0.03  393.0  2388.0  100.0   
3  14.62  ...  521.38  2388.05  8132.90  8.3917  0.03  391.0  2388.0  100.0   
4  14.62  ...  522.15  2388.03  8129.54  8.4031  0.03  390.0  2388.0  100.0   

     s20      s21  
0  38.86  23.3735  
1  39.02  23.3916  
2  39.08  23.4166  
3  39.00  23.3737  
4  38.99  23.4130  

[5 rows x 26 columns]

In [37]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='XeaAWDu0NTFq6Wd1KkU_9kiMsC5f8bAki0X4MI77fHRP',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'ibmdepolyment-donotdelete-pr-mut3vz0xh6wsjn'
object_key = 'PM_truth.xlsx'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']

pm_truth = pd.read_excel(body.read())
pm_truth.head()


more  id
0   112   1
1    98   2
2    69   3
3    82   4
4    91   5

In [38]:
rul=pd.DataFrame(dataset_test.groupby('id')['cycle'].max()).reset_index()
rul.columns=['id','max']
rul.head()

id  max
0   1   31
1   2   49
2   3  126
3   4  106
4   5   98

In [39]:
pm_truth['rtf']=pm_truth['more']+rul['max']
pm_truth.head()

more  id    rtf
0   112   1  143.0
1    98   2  147.0
2    69   3  195.0
3    82   4  188.0
4    91   5  189.0

In [40]:
pm_truth.drop('more',axis=1,inplace=True)
dataset_test=dataset_test.merge(pm_truth,on=['id'],how='left')
dataset_test['ttf']=dataset_test['rtf']-dataset_test['cycle']
dataset_test.drop('rtf',axis=1,inplace=True)
dataset_test.head()

id  cycle  setting1  setting2  setting3      s1      s2       s3       s4  \
0   1      1    0.0023    0.0003       100  518.67  643.02  1585.29  1398.21   
1   1      2   -0.0027   -0.0003       100  518.67  641.71  1588.45  1395.42   
2   1      3    0.0003    0.0001       100  518.67  642.46  1586.94  1401.34   
3   1      4    0.0042    0.0000       100  518.67  642.44  1584.12  1406.42   
4   1      5    0.0014    0.0000       100  518.67  642.51  1587.19  1401.92   

      s5  ...      s13      s14     s15   s16    s17     s18    s19    s20  \
0  14.62  ...  2388.03  8125.55  8.4052  0.03  392.0  2388.0  100.0  38.86   
1  14.62  ...  2388.06  8139.62  8.3803  0.03  393.0  2388.0  100.0  39.02   
2  14.62  ...  2388.03  8130.10  8.4441  0.03  393.0  2388.0  100.0  39.08   
3  14.62  ...  2388.05  8132.90  8.3917  0.03  391.0  2388.0  100.0  39.00   
4  14.62  ...  2388.03  8129.54  8.4031  0.03  390.0  2388.0  100.0  38.99   

       s21    ttf  
0  23.3735  142.0  
1  23.3916  141.0  
2  23.4166  140.0  
3  23.3737  139.0  
4  23.4130  138.0  

[5 rows x 27 columns]

In [41]:
dataset_train['ttf']=dataset_train.groupby(['id'])['cycle'].transform(max)-dataset_train['cycle']
dataset_train.head()

id  cycle  setting1  setting2  setting3      s1      s2       s3       s4  \
0   1      1   -0.0007   -0.0004       100  518.67  641.82  1589.70  1400.60   
1   1      2    0.0019   -0.0003       100  518.67  642.15  1591.82  1403.14   
2   1      3   -0.0043    0.0003       100  518.67  642.35  1587.99  1404.20   
3   1      4    0.0007    0.0000       100  518.67  642.35  1582.79  1401.87   
4   1      5   -0.0019   -0.0002       100  518.67  642.37  1582.85  1406.22   

      s5  ...      s13      s14     s15   s16  s17   s18  s19    s20      s21  \
0  14.62  ...  2388.02  8138.62  8.4195  0.03  392  2388  100  39.06  23.4190   
1  14.62  ...  2388.07  8131.49  8.4318  0.03  392  2388  100  39.00  23.4236   
2  14.62  ...  2388.03  8133.23  8.4178  0.03  390  2388  100  38.95  23.3442   
3  14.62  ...  2388.08  8133.83  8.3682  0.03  392  2388  100  38.88  23.3739   
4  14.62  ...  2388.04  8133.80  8.4294  0.03  393  2388  100  38.90  23.4044   

   ttf  
0  191  
1  190  
2  189  
3  188  
4  187  

[5 rows x 27 columns]

In [42]:
df_train=dataset_train.copy()
df_test=dataset_test.copy()
period=30
df_train['label_bc']=df_train['ttf'].apply(lambda x: 1 if x <= period else 0)
df_test['label_bc']=df_test['ttf'].apply(lambda x: 1 if x <= period else 0)
df_train.head()

id  cycle  setting1  setting2  setting3      s1      s2       s3       s4  \
0   1      1   -0.0007   -0.0004       100  518.67  641.82  1589.70  1400.60   
1   1      2    0.0019   -0.0003       100  518.67  642.15  1591.82  1403.14   
2   1      3   -0.0043    0.0003       100  518.67  642.35  1587.99  1404.20   
3   1      4    0.0007    0.0000       100  518.67  642.35  1582.79  1401.87   
4   1      5   -0.0019   -0.0002       100  518.67  642.37  1582.85  1406.22   

      s5  ...      s14     s15   s16  s17   s18  s19    s20      s21  ttf  \
0  14.62  ...  8138.62  8.4195  0.03  392  2388  100  39.06  23.4190  191   
1  14.62  ...  8131.49  8.4318  0.03  392  2388  100  39.00  23.4236  190   
2  14.62  ...  8133.23  8.4178  0.03  390  2388  100  38.95  23.3442  189   
3  14.62  ...  8133.83  8.3682  0.03  392  2388  100  38.88  23.3739  188   
4  14.62  ...  8133.80  8.4294  0.03  393  2388  100  38.90  23.4044  187   

   label_bc  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 28 columns]

In [43]:
x_train=df_train.iloc[:,:-1].values
y_train=df_train.iloc[:,-1:].values

In [44]:
#Splitting data into train  and test
from scipy.sparse.construct import random
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_train,y_train,test_size=0.2,random_state=0)

In [45]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [46]:
y_pred1=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)
log_reg

0.9983038526774897

In [47]:
from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(y_test,y_pred1)
cm1

array([[3515,    2],
       [   5,  605]])

In [48]:
import joblib
joblib.dump(lr, "engine_model.sav")

['engine_model.sav']

In [49]:
!pip install ibm_watson_machine_learning


In [76]:
from ibm_watson_machine_learning import APIClient
wml_credentials={
    "url":"https://us-south.ml.cloud.ibm.com",
    "apikey" :"lXz0XO1eh1nLZZLQ2m7wahlFW812sFxvI5d80PVEQAz9"
}
client=APIClient(wml_credentials)

In [79]:
def guid_from_space_name(client, space_name):
    space = client.spaces.get_details()
    return(next(item for item in space['resources'] if item ['entity']['name'] == space_name)['metadata']['id'])


In [80]:
space_uid = guid_from_space_name (client, 'model')
print("Space UID ="+ space_uid)
client.set.default_space(space_uid)

Space UID =c0d5d31d-a37a-4da4-9fc0-7c17a737cd6c


'SUCCESS'

In [83]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

In [88]:
software_spec_uid = client.software_specifications.get_uid_by_name("runtime-22.1-py3.9")
software_spec_uid

'12b83a17-24d8-5082-900f-0ab31fbfd3cb'

In [93]:
model_details = client.repository.store_model(model=lr,meta_props ={
    client.repository.ModelMetaNames.NAME:"engine_model",
    client.repository.ModelMetaNames.TYPE:"scikit-learn_1.0",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid
    
})
model_id=client.repository.get_model_uid(model_details)

This method is deprecated, please use get_model_id()


In [94]:
model_id

'bfc4e459-aeec-4b13-81a3-975be21e8dcd'

In [95]:
x_train[0]

array([ 2.70000e+01,  1.08000e+02, -4.80000e-03,  0.00000e+00,
        1.00000e+02,  5.18670e+02,  6.42500e+02,  1.58658e+03,
        1.41020e+03,  1.46200e+01,  2.16100e+01,  5.53290e+02,
        2.38810e+03,  9.07818e+03,  1.30000e+00,  4.74700e+01,
        5.21280e+02,  2.38810e+03,  8.15268e+03,  8.44090e+00,
        3.00000e-02,  3.94000e+02,  2.38800e+03,  1.00000e+02,
        3.87300e+01,  2.33405e+01,  4.80000e+01])

In [97]:
lr.predict([[ 2.70000e+01,  1.08000e+02, -4.80000e-03,  0.00000e+00,
        1.00000e+02,  5.18670e+02,  6.42500e+02,  1.58658e+03,
        1.41020e+03,  1.46200e+01,  2.16100e+01,  5.53290e+02,
        2.38810e+03,  9.07818e+03,  1.30000e+00,  4.74700e+01,
        5.21280e+02,  2.38810e+03,  8.15268e+03,  8.44090e+00,
        3.00000e-02,  3.94000e+02,  2.38800e+03,  1.00000e+02,
        3.87300e+01,  2.33405e+01,  4.80000e+01]])

array([0])